### ISSUE TITLE
MySQL server does not start

### ISSUE THREAD

**Issue by LalaDK** [ansibleguy76/ansibleforms-docker#12]
Hello. 

I am trying this out for the first time, but I can't get it to work. Here is the docker compose logs:
```
af_app  | 2025-06-11 12:32:04:324 info: Waiting for mysql to start
af_app  | 2025-06-11 12:32:04:324 error: [ansibleforms] Connection error : Error: getaddrinfo ENOTFOUND mysqldb
af_app  | 2025-06-11 12:32:04:324 warning: Mysql not ready yet
af_db   | 2025-06-11 12:32:05+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
af_db   | 2025-06-11 12:32:05+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.5-1.el9 started.
af_db   | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
af_db   | 2025-06-11T12:32:05.680369Z 0 [System] [MY-015015] [Server] MySQL Server - start.
af_db   | 2025-06-11T12:32:05.943107Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.4.5) starting as process 1
af_db   | 2025-06-11T12:32:05.951001Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
af_db   | 2025-06-11T12:32:06.504286Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
af_db   | mysqld: Table 'mysql.plugin' doesn't exist
af_db   | 2025-06-11T12:32:06.691533Z 0 [ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
af_db   | 2025-06-11T12:32:06.691934Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.692172Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.692357Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.692650Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.692978Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.693151Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.693340Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.746353Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
af_db   | 2025-06-11T12:32:06.820477Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
af_db   | 2025-06-11T12:32:06.825512Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
af_db   | 2025-06-11T12:32:06.825544Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
af_db   | 2025-06-11T12:32:06.829049Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
af_db   | 2025-06-11T12:32:06.829697Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
af_db   | 2025-06-11T12:32:06.829996Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
af_db   | 2025-06-11T12:32:06.830017Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
af_db   | 2025-06-11T12:32:06.830125Z 0 [ERROR] [MY-000067] [Server] unknown variable 'default_authentication_plugin=caching_sha2_password'.
af_db   | 2025-06-11T12:32:06.830907Z 0 [ERROR] [MY-010119] [Server] Aborting
af_db   | 2025-06-11T12:32:08.459700Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.4.5)  MySQL Community Server - GPL.
af_db   | 2025-06-11T12:32:08.459725Z 0 [System] [MY-015016] [Server] MySQL Server - end.
af_db exited with code 1
```

**Comment by LalaDK** [comment]
I am trying to deploy Ansible Forms with Ansible:
```yaml
- name: Ensure destination directory exists
  ansible.builtin.file:
    path:
      - "{{ project_diretory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Clone the repository
  ansible.builtin.git:
    repo: "https://github.com/ansibleguy76/ansibleforms-docker.git"
    dest: "{{ project_diretory }}"
    version: main
    force: yes
    update: yes

- name: Set file and directory permissions recursively to 664 under ./data
  ansible.builtin.command: chmod -R 664 ./data
  args:
    chdir: "{{ project_diretory }}"

- name: Ensure execute permissions on ./data/mysql/init
  ansible.builtin.command: chmod -R +x ./data/mysql/init
  args:
    chdir: "{{ project_diretory }}"

- name: Run Docker Compose
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ project_diretory }}"
```
